
#.
#Control certain aspects of the Mechanical Insolator
[insolator]
	#.
	#.
	#Controls the multiplier of a given processing recipe.
	#Range: > 1
	"Processing Time Multiplier" = 1
	#.
	#Controls the tank size of the Mechanical Insolator.
	#Requires you to break and replace the block in order to update blockstate.
	#Range: 1000 ~ 16000
	"Tank Size" = 1000
	#.
	#The kinetic stress impact value
	#Requires you to break and replace the block in order to update blockstate.
	#Range: > 2
	"Kinetic Stress Impact" = 64

#.
#Control certain aspects of the Mechanical Composter
[composter]
	#.
	#.
	#Controls the multiplier of a given processing recipe.
	#Range: > 1
	"Processing Time Multiplier" = 1
	#.
	#The kinetic stress impact value
	#Requires you to break and replace the block in order to update blockstate.
	#Range: > 2
	"Kinetic Stress Impact" = 16

