
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 0
	#The name of the modpack
	modpackName = "TiozinNub's Pack"
	#The version of the modpack
	modpackVersion = "5.2.2-dev20251024-164029"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

